defaults:
  - _self_
  - compnode: light_1n_1g_28b.yaml
  - model: nerf.yaml
  - datamodule: lego.yaml
  - jaws: batch.yaml

#########################################################
#           Parameters

# num of sanity checking step
num_sanity_val_steps: 0
# num of epochs
num_epochs: 501
# num of training epoch after validation
check_val_every_n_epoch: 50
# num rays sampled per image for each training step
num_rays: 4096
# num steps sampled per ray
num_steps: 128
# num steps up-sampled per ray
upsample_steps: 0
# batch size of rays at inference to avoid OOM
max_ray_batch: 4096
# num of checkpoints to keep
num_checkpoints: 2
# Type of run to launch (current: train TODO: debug/eval/infer/...)
run_type: jaws
dynamic: false
error_map: false
saturation_loss: false
floater_ratio: 0

aabb: 1.0
#########################################################
#              Wandb
# Name of the project is accessed by loggers
project_name: jaws
# Name of the run is accessed by loggers
xp_name: ${xp_name}
# Name of the group by loggers
group_name: 3imgs_translation_z
# Name of the job type
job_type: null
# Wether to synced the logs or not (WandB)
log_offline: false
# Metric to monitor to save models
checkpoint_metric: train/loss

#########################################################
#            Hydra
root: ${hydra:runtime.cwd}
# Path to folder with data
data_dir: ${data_dir}
# Path to folder to save results
result_dir: ${root}/results/${xp_name}


# Pretty print config at the start of the run using Rich library
print_config: True

hydra:
  run:
    dir: ${hydra:runtime.cwd}/logs
  output_subdir: null
  sweep:
    dir: ${hydra:runtime.cwd}/logs
    subdir: ${hydra:runtime.cwd}/logs

#########################################################
#            System
# Disable (or not) python warnings
ignore_warnings: True
device: cuda
# Seed for random number generators
seed: 1