# initial learning rate
lr: 1e-2
lr_net: 1e-3
ckpt: "latest"
# use amp mixed precision training
fp16: True

warp_encoding: frequency
time_encoding: frequency
sigma_encoding: tiledgrid
direction_encoding: sphere_harmonics
background_encoding: hashgrid
n_warp_layers: 7
n_sigma_layers: 5
n_color_layers: 5
n_background_layers: 2
warp_hidden_dim: 128
sigma_hidden_dim: 128
color_hidden_dim: 128
background_hidden_dim: 128
geo_feat_dim: 15

raft_checkpoint: ${root}/checkpoints/raft-things.pth
encoder_checkpoint: ${root}/checkpoints/autoencoder-mse-unit-224-noskip-490-last.ckpt
model_size: small
encoder_num_levels: 32